# This action pushes new amd64 and arm64 docker images to the Docker and GitHub
# registries on every new release of the project.
#
# Cobbled together from these sources:
# - https://github.com/docker/build-push-action/#usage
# - https://docs.github.com/en/actions/publishing-packages/publishing-docker-images

name: Release

"on":
  release:
    types: [published]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: mccutchen
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: mccutchen
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            mccutchen/kafka-lite
            ghrc.io/mccutchen/kafka-lite

      - name: Compute build args
        id: args
        run: |
          build_args="$(grep KAFKA_VERSION VERSIONS)"
          build_args="${build_args},$(grep SCALA_VERSION VERSIONS)"
          echo "build_args=$build_args" >> $GITHUB_OUTPUT

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: ${{ steps.args.outputs.build_args }}
